CREATE DATABASE QUAN_LY_BAN_VE_MAY_BAY
USE QUAN_LY_BAN_VE_MAY_BAY
--------------------------------------------------
-- MODULE 1: NGƯỜI DÙNG
CREATE TABLE KHACH_HANG (
	MA_KH VARCHAR(10) PRIMARY KEY,
	TEN_KH NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	SDT_KH VARCHAR(15) UNIQUE,
	DIACHI NVARCHAR(200)
);

CREATE TABLE NHAN_VIEN(
	MA_NV VARCHAR(10) PRIMARY KEY,
	TEN_NV NVARCHAR(100) NOT NULL,
	CHUCVU NVARCHAR(100),
	SDT_NV VARCHAR(15) UNIQUE
);

CREATE TABLE NGUOI_DUNG(
    USERNAME VARCHAR(50) PRIMARY KEY,
    MAT_KHAU VARCHAR(50),
    VAI_TRO VARCHAR(2),
	MA_KH VARCHAR(10),
	MA_NV VARCHAR(10),
	FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
	FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV)
);

--------------------------------------------------
-- MODULE 2: CHUYẾN BAY
CREATE TABLE HANG_BAY (
	MA_HANG VARCHAR(10) PRIMARY KEY,
	TEN_HANG NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE MAY_BAY (
	MA_MB VARCHAR(10) PRIMARY KEY,
	MA_HANG VARCHAR(10) NOT NULL,
	TEN_MB NVARCHAR(100),
	FOREIGN KEY (MA_HANG) REFERENCES HANG_BAY(MA_HANG)
);

CREATE TABLE SAN_BAY (
	MA_SB VARCHAR(10) PRIMARY KEY,
	TEN_SB NVARCHAR(100) UNIQUE NOT NULL,
	THANH_PHO NVARCHAR(100)
);

CREATE TABLE CHUYEN_BAY (
	MA_CB VARCHAR(10) PRIMARY KEY,
	MA_MB VARCHAR(10),
	SB_DI VARCHAR(10) NOT NULL,
	SB_DEN VARCHAR(10) NOT NULL,
	NGAY_BAY DATETIME,
	FOREIGN KEY (MA_MB) REFERENCES MAY_BAY(MA_MB),
	FOREIGN KEY (SB_DI) REFERENCES SAN_BAY(MA_SB),
	FOREIGN KEY (SB_DEN) REFERENCES SAN_BAY(MA_SB),
	CHECK (SB_DI <> SB_DEN)
);

--------------------------------------------------
-- MODULE 3: GHẾ & VÉ
CREATE TABLE HANG_GHE(
	MA_HANG_GHE VARCHAR(10) PRIMARY KEY,
	TEN_HANG_GHE NVARCHAR(100) NOT NULL
);

CREATE TABLE GHE(
	MA_GHE VARCHAR(10) PRIMARY KEY,
	MA_HANG_GHE VARCHAR(10),
	SO_GHE VARCHAR(10) NOT NULL,
	FOREIGN KEY (MA_HANG_GHE) REFERENCES HANG_GHE(MA_HANG_GHE),
	UNIQUE (MA_HANG_GHE, SO_GHE)
);

--------------------------------------------------
-- MODULE 4: THANH TOÁN (TẠO TRƯỚC để VE tham chiếu)
CREATE TABLE KHUYEN_MAI(
	MA_KM VARCHAR(10) PRIMARY KEY,
	TEN_KM NVARCHAR(100),
	PHAN_TRAM_GIAM_GIA DECIMAL(5,2),
	NGAY_BD DATETIME,
	NGAY_KT DATETIME,
	CHECK (NGAY_KT >= NGAY_BD)
);

CREATE TABLE HOA_DON(
	MA_HOA_DON VARCHAR(10) PRIMARY KEY,
	MA_KM VARCHAR(10),
	NGAY_TAO DATETIME DEFAULT GETDATE(),
	TONG_TIEN DECIMAL(15,2),
	FOREIGN KEY (MA_KM) REFERENCES KHUYEN_MAI(MA_KM)
);

--------------------------------------------------
--QUAN TRỌNG: VE tạo sau HOA_DON
CREATE TABLE VE(
	MA_VE VARCHAR(10) PRIMARY KEY,
	MA_KH VARCHAR(10) NOT NULL,
	MA_CB VARCHAR(10) NOT NULL,
	MA_GHE VARCHAR(10) NOT NULL,
	MA_HOA_DON VARCHAR(10),
	NGAY_MUA DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
	FOREIGN KEY (MA_CB) REFERENCES CHUYEN_BAY(MA_CB),
	FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE),
	FOREIGN KEY (MA_HOA_DON) REFERENCES HOA_DON(MA_HOA_DON),
	UNIQUE (MA_CB, MA_GHE)
);

CREATE TABLE DAT_CHO(
	MA_DAT_CHO VARCHAR(10) PRIMARY KEY,
	MA_KH VARCHAR(10),
	MA_CB VARCHAR(10),
	MA_GHE VARCHAR(10),
	THOI_GIAN DATETIME DEFAULT GETDATE(),
	TRANG_THAI NVARCHAR(50),
	FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
	FOREIGN KEY (MA_CB) REFERENCES CHUYEN_BAY(MA_CB),
	FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE),
	UNIQUE (MA_CB, MA_GHE)
);

CREATE TABLE THANH_TOAN(
	MA_TT VARCHAR(10) PRIMARY KEY,
	MA_HOA_DON VARCHAR(10) UNIQUE,
	PHUONG_THUC NVARCHAR(50),
	NGAY_THANH_TOAN DATETIME DEFAULT GETDATE(),
	SO_TIEN_DA_TRA DECIMAL(15,2),
	FOREIGN KEY (MA_HOA_DON) REFERENCES HOA_DON(MA_HOA_DON)
);

CREATE TABLE HANH_LY(
	MA_HL VARCHAR(10) PRIMARY KEY,
	MA_VE VARCHAR(10),
	KHOI_LUONG FLOAT,
	GIA_TIEN DECIMAL(15,2),
	FOREIGN KEY (MA_VE) REFERENCES VE(MA_VE)
);

CREATE TABLE BANG_GIA(
	MA_BG VARCHAR(10) PRIMARY KEY,
	MA_CB VARCHAR(10),
	MA_HANG_GHE VARCHAR(10),
	GIA_TIEN DECIMAL(15,2),
	FOREIGN KEY (MA_CB) REFERENCES CHUYEN_BAY(MA_CB),
	FOREIGN KEY (MA_HANG_GHE) REFERENCES HANG_GHE(MA_HANG_GHE)
);

--------------------------------------------------
-- MODULE 5
CREATE TABLE AUDIT_LOG(
	LOG_ID INT PRIMARY KEY,
	HANH_DONG NVARCHAR(50),
	THOI_GIAN_TAO DATETIME DEFAULT GETDATE(),
	MO_TA NVARCHAR(200)
);
--THÊM DỮ LIỆU
--1. HÃNG BAY
INSERT INTO HANG_BAY VALUES
('HB01', N'Vietnam Airlines'),
('HB02', N'Vietjet Air'),
('HB03', N'Bamboo Airways');
--2. SÂN BAY
INSERT INTO SAN_BAY VALUES
('SB01', N'Nội Bài', N'Hà Nội'),
('SB02', N'Tân Sơn Nhất', N'HCM'),
('SB03', N'Đà Nẵng', N'Đà Nẵng'),
('SB04', N'Cam Ranh', N'Khánh Hòa'),
('SB05', N'Phú Quốc', N'Kiên Giang');
--3. HẠNG GHẾ
INSERT INTO HANG_GHE VALUES
('HG1', N'Phổ thông'),
('HG2', N'Thương gia');
--4. MÁY BAY
INSERT INTO MAY_BAY VALUES
-- Vietnam Airlines
('MB01','HB01',N'Airbus A321'),
('MB02','HB01',N'Boeing 787 Dreamliner'),
('MB03','HB01',N'Airbus A350'),

-- Vietjet Air
('MB04','HB02',N'Airbus A320'),
('MB05','HB02',N'Airbus A321 Neo'),
('MB06','HB02',N'Boeing 737 Max'),

-- Bamboo Airways
('MB07','HB03',N'Airbus A321'),
('MB08','HB03',N'Boeing 787-9'),
('MB09','HB03',N'Embraer E190'),

-- KHÁC
('MB10','HB01',N'ATR 72'),
('MB11','HB02',N'Airbus A319'),
('MB12','HB03',N'Airbus A320 Neo');
--5. CHUYẾN BAY
INSERT INTO CHUYEN_BAY VALUES
('CB01','MB01','SB01','SB02','2026-05-01'),
('CB02','MB02','SB02','SB01','2026-05-02'),
('CB03','MB03','SB01','SB03','2026-05-03'),
('CB04','MB04','SB03','SB04','2026-05-04'),
('CB05','MB05','SB02','SB05','2026-05-05'),
('CB06','MB06','SB05','SB01','2026-05-06'),
('CB07','MB07','SB01','SB02','2026-05-07'),
('CB08','MB08','SB02','SB03','2026-05-08'),
('CB09','MB09','SB03','SB01','2026-05-09'),
('CB10','MB10','SB04','SB02','2026-05-10');
--6. GHẾ
INSERT INTO GHE VALUES
('G01','HG1','A1'),
('G02','HG1','A2'),
('G03','HG1','A3'),
('G04','HG2','B1'),
('G05','HG2','B2'),
('G06','HG1','A4'),
('G07','HG1','A5'),
('G08','HG2','B3'),
('G09','HG2','B4'),
('G10','HG1','A6');
--7. KHÁCH HÀNG
INSERT INTO KHACH_HANG VALUES
('KH01',N'Nguyễn Minh Anh','minhanh.nguyen01@gmail.com','0901000001',N'Hà Nội'),
('KH02',N'Trần Quốc Bảo','quocbao.tran02@gmail.com','0901000002',N'Hồ Chí Minh'),
('KH03',N'Lê Thu Cúc','thucuc.le03@gmail.com','0901000003',N'Đà Nẵng'),
('KH04',N'Phạm Gia Duy','giaduy.pham04@gmail.com','0901000004',N'Hải Phòng'),
('KH05',N'Hoàng Ngọc Diệp','ngocdiep.hoang05@gmail.com','0901000005',N'Cần Thơ'),
('KH06',N'Nguyễn Hoàng Long','hoanglong.nguyen06@gmail.com','0901000006',N'Huế'),
('KH07',N'Trần Thị Hạnh','thihanh.tran07@gmail.com','0901000007',N'Nha Trang'),
('KH08',N'Lê Văn Nam','vannam.le08@gmail.com','0901000008',N'Nghệ An'),
('KH09',N'Phạm Tuấn Kiệt','tuankiet.pham09@gmail.com','0901000009',N'Quảng Ninh'),
('KH10',N'Hoàng Minh Khoa','minhkhoa.hoang10@gmail.com','0901000010',N'Bắc Ninh');
--8. NHÂN VIÊN
INSERT INTO NHAN_VIEN VALUES
('NV01',N'Admin 1',N'Quản lý','0911111111'),
('NV02',N'Admin 2',N'Nhân viên','0911111112');
--9. NGƯỜI DÙNG
INSERT INTO NGUOI_DUNG VALUES
('user1','123','KH','KH01',NULL),
('user2','123','KH','KH02',NULL),
('admin','123','NV',NULL,'NV01');
--10. KHUYẾN MÃI
INSERT INTO KHUYEN_MAI VALUES
('KM01',N'Giảm 10%',10,'2026-01-01','2026-12-31'),
('KM02',N'Giảm 20%',20,'2026-01-01','2026-12-31');
--11. HÓA ĐƠN
INSERT INTO HOA_DON VALUES
('HD01','KM01',GETDATE(),1000000),
('HD02','KM02',GETDATE(),1500000),
('HD03',NULL,GETDATE(),2000000);
--12. VÉ
INSERT INTO VE(MA_VE,MA_KH,MA_CB,MA_GHE,MA_HOA_DON) VALUES
('VE01','KH01','CB01','G01','HD01'),
('VE02','KH02','CB02','G02','HD02'),
('VE03','KH03','CB03','G03','HD03');
--13. ĐẶT CHỖ
INSERT INTO DAT_CHO VALUES
('DC01','KH04','CB04','G04',GETDATE(),N'Đã đặt'),
('DC02','KH05','CB05','G05',GETDATE(),N'Đã đặt');
--14. THANH TOÁN
INSERT INTO THANH_TOAN VALUES
('TT01','HD01',N'Tiền mặt',GETDATE(),1000000),
('TT02','HD02',N'Chuyển khoản',GETDATE(),1500000),
('TT03','HD03',N'Tiền mặt',GETDATE(),2000000);
--15. HÀNH LÝ
INSERT INTO HANH_LY VALUES
('HL01','VE01',20,200000),
('HL02','VE02',15,150000);
--16. BẢNG GIÁ
INSERT INTO BANG_GIA VALUES
('BG01','CB01','HG1',1000000),
('BG02','CB01','HG2',2000000),
('BG03','CB02','HG1',1200000),
('BG04','CB02','HG2',2200000);

--THỦ TỤC, TRIGGER, FUNTIONS
GO
CREATE OR ALTER PROC SP_LOGIN
    @USERNAME VARCHAR(50),
    @MAT_KHAU VARCHAR(50)
AS
BEGIN
    -- Kiểm tra tài khoản tồn tại
    IF NOT EXISTS (
        SELECT 1 FROM NGUOI_DUNG 
        WHERE USERNAME = @USERNAME
    )
    BEGIN
        PRINT N'Tài khoản không tồn tại';
        RETURN;
    END

    -- Kiểm tra mật khẩu
    IF NOT EXISTS (
        SELECT 1 FROM NGUOI_DUNG 
        WHERE USERNAME = @USERNAME AND MAT_KHAU = @MAT_KHAU
    )
    BEGIN
        PRINT N'Sai mật khẩu';
        RETURN;
    END

    -- Login thành công
    SELECT 
        USERNAME,
        VAI_TRO,
        MA_KH,
        MA_NV
    FROM NGUOI_DUNG
    WHERE USERNAME = @USERNAME AND MAT_KHAU = @MAT_KHAU;

    PRINT N'Đăng nhập thành công';
END
--1--Trigger kiểm tra ghế đã được đặt hoặc bán hay chưa
CREATE TRIGGER TG_CheckGheTruocKhiDat
ON DAT_CHO
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INSERTED i
        JOIN VE v 
        ON i.MA_CB = v.MA_CB AND i.MA_GHE = v.MA_GHE
    )
    BEGIN
        PRINT N'Ghế này đã được bán!';
        ROLLBACK;
        RETURN;
    END

    INSERT INTO DAT_CHO
    SELECT * FROM INSERTED;
END

INSERT INTO DAT_CHO(MA_DAT_CHO, MA_KH, MA_CB, MA_GHE)
VALUES('DC01', 'KH01', 'CB01', 'G01'); --Thông báo: Ghế này đã được bán

INSERT INTO VE(MA_VE, MA_KH, MA_CB, MA_GHE)
VALUES('V001', 'KH01', 'CB01', 'G01');--Đặt vé mới và Trigger ghi lại
GO
--Lịch sử hoạt động
--2--Trigger tự động ghi log khi thêm vé
CREATE TRIGGER TRG_LogThemVe
ON VE
AFTER INSERT
AS
BEGIN
    INSERT INTO AUDIT_LOG(HANH_DONG, MO_TA)
    SELECT 
        N'THÊM VÉ',
        N'Thêm vé: ' + MA_VE
    FROM INSERTED;
END
GO

--3--Trigger Cập nhật tổng tiền hóa đơn khi thêm vé
CREATE TRIGGER TG_UpdateTongTien
ON VE
AFTER INSERT
AS
BEGIN
    UPDATE HOA_DON
    SET TONG_TIEN = (
        SELECT SUM(bg.GIA_TIEN)
        FROM VE v
        JOIN CHUYEN_BAY cb ON v.MA_CB = cb.MA_CB
        JOIN GHE g ON v.MA_GHE = g.MA_GHE
        JOIN BANG_GIA bg 
            ON bg.MA_CB = v.MA_CB 
            AND bg.MA_HANG_GHE = g.MA_HANG_GHE
        WHERE v.MA_HOA_DON = HOA_DON.MA_HOA_DON
    )
    WHERE MA_HOA_DON IN (SELECT MA_HOA_DON FROM INSERTED);
END
GO
--4--Trigger kiểm tra khuyến mãi còn hạn hay không
CREATE TRIGGER TRG_KiemTraKhuyenMai
ON HOA_DON
AFTER INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INSERTED i
        JOIN KHUYEN_MAI km ON i.MA_KM = km.MA_KM
        WHERE GETDATE() NOT BETWEEN km.NGAY_BD AND km.NGAY_KT
    )
    BEGIN
        PRINT N'Khuyến mãi không còn hiệu lực!';
        ROLLBACK;
    END
END
GO
--Thủ tục đặt vé
CREATE PROC P_DatVe
    @MA_VE VARCHAR(10),
    @MA_KH VARCHAR(10),
    @MA_CB VARCHAR(10),
    @MA_GHE VARCHAR(10),
    @MA_HOA_DON VARCHAR(10)
AS
BEGIN
    -- kiểm tra ghế
    IF EXISTS (
        SELECT 1 FROM VE 
        WHERE MA_CB = @MA_CB AND MA_GHE = @MA_GHE
    )
    BEGIN
        PRINT N'Ghế đã được đặt!';
        RETURN;
    END

    INSERT INTO VE
    VALUES(@MA_VE, @MA_KH, @MA_CB, @MA_GHE, @MA_HOA_DON, GETDATE());

    PRINT N'Đặt vé thành công';
END
GO
--Thủ tục thanh toán
CREATE PROC P_ThanhToan
    @MA_TT VARCHAR(10),
    @MA_HOA_DON VARCHAR(10),
    @SO_TIEN DECIMAL(15,2)
AS
BEGIN
    DECLARE @TONG DECIMAL(15,2);

    SELECT @TONG = TONG_TIEN 
    FROM HOA_DON 
    WHERE MA_HOA_DON = @MA_HOA_DON;

    IF @SO_TIEN < @TONG
    BEGIN
        PRINT N'Chưa thanh toán đủ tiền!';
        RETURN;
    END

    INSERT INTO THANH_TOAN
    VALUES(@MA_TT, @MA_HOA_DON, N'Tiền mặt', GETDATE(), @SO_TIEN);

    PRINT N'Thanh toán thành công';
END
GO
--Thủ tục tìm chuyến bay
CREATE PROC P_TimChuyenBay
    @SB_DI VARCHAR(10),
    @SB_DEN VARCHAR(10)
AS
BEGIN
    SELECT *
    FROM CHUYEN_BAY
    WHERE SB_DI = @SB_DI AND SB_DEN = @SB_DEN;
END
GO
--Thủ tục hủy vé
CREATE PROC P_HuyVe
    @MA_VE VARCHAR(10)
AS
BEGIN
    DELETE FROM VE WHERE MA_VE = @MA_VE;

    PRINT N'Đã hủy vé';
END
GO

